### ISSUE TITLE
People App - Roadmap

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/People#100]
This represents the Roadmap for all fixes, new functionalities and enhancements related to People app. 

1. [x] 1. Investigating and fixing different bugs  -  ~~https://github.com/StarcounterApps/People/issues/93~~ ~~https://github.com/StarcounterApps/People/issues/94~~ ~~https://github.com/StarcounterApps/People/issues/98~~<p>
2. [x] 2. Fix  odd behaviour within the Images App  - ~~https://github.com/StarcounterApps/People/issues/95~~  ~~https://github.com/StarcounterApps/People/issues/97~~<p>
3. [x] 3. Implement the new design - https://github.com/StarcounterApps/People/issues/92
   1. [x] 1. Add control on related organizations to the single person vue  
   2. [x] 2. Add new properties to Person Entity (Birthdate, Nationality)
   3. [x] 3. Extend People with tags #103 
   4. [x] 4. Improve the single person vue and styles<p>
4. [x] 4. Make a similar composition within different Crm apps like proposed in -
 https://github.com/Starcounter/RebelsLounge/issues/121<p>
5. [x] 5. Iron-collapse is not in bower.json #104 <p>
6. [x] 6. Add info about being unauthenticated user #105 <p>
7. [x] 7. Apply the new design to single organization view #111  <p>
8. [x] 8. Fix pagination issue #112  <p>
9. [x] 9. Release a bug-free/re-designed version <p>
10. [x] 10. Deploy the new release on `inside.starcounter.com` <p>
11. [x] 11. make changes according to new design #126 <p>

**Comment by bouguila** [comment]
closing as completed.
